name: dac

channels:
  - defaults
  - conda-forge

dependencies:
  - pip
  - python=3.10
  - ffmpeg>=4.2,<5
  - pytorch::pytorch>=2=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch::torchaudio>=2
  - nvidia::cudatoolkit=11.7

  - pip:
    - -e .
